<header id="header">
	<hgroup>
		<h1 class="site_title"><a href="/">La Rocca</a></h1>
		<h2 class="section_title">Дневник на брокера</h2>
	</hgroup>
</header> <!-- end of header bar -->

<section id="secondary_bar">
	<div class="user">
		<p><?=$this->user?></p>
	</div>
	<div class="breadcrumbs_container">
		<article class="breadcrumbs">
            <a href="/">Начало</a> <div class="breadcrumb_divider"></div> 
            <a class="current">Добавяне на запис</a>
        </article>
	</div>
</section><!-- end of secondary bar -->