<header id="header">
	<hgroup>
		<h1 class="site_title"><a href="index.html">La Rocca</a></h1>
		<h2 class="section_title">Дневник на брокера</h2>
	</hgroup>
</header> <!-- end of header bar -->

<section id="secondary_bar">
	<div class="user">
		<p>Светлин Тачев</p>
	</div>
	<div class="breadcrumbs_container">
		<article class="breadcrumbs">
            <a href="index.html">Начало</a> <div class="breadcrumb_divider"></div> 
            <a class="current">Добавяне на запис</a>
        </article>
	</div>
</section><!-- end of secondary bar -->