<aside id="sidebar" class="column">
	<form class="quick_search">
		<input type="text" value="Бързо търсене" onfocus="if(!this._haschanged){this.value=''};this._haschanged=true;">
	</form>
	<hr/>
	<h3>Записи</h3>
	<ul class="toggle">
		<li class="icn_new_article"><a href="#">Добавяне на запис</a></li>
		<li class="icn_edit_article"><a href="#">Редактиране на записи</a></li>
	</ul>
			
	<footer>
		<hr />
		<p><strong>Copyright &copy; 2012 Sasquatch </strong></p>
		<p><a href="http://www.bgscripts.com">www.bgscripts.com</a></p>
	</footer>
</aside><!-- end of sidebar -->
