<!doctype html>
<html lang="en">

<head>
	<meta charset="utf-8"/>
	<title><?php echo $this->escape($this->title); ?></title>
	
	<link rel="stylesheet" href="<?php echo $this->baseUrl('css/layout.css'); ?>" type="text/css" media="screen" />
	<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/smoothness/jquery-ui.css" type="text/css" media="screen" />   
	<!--[if lt IE 9]>
	<link rel="stylesheet" href="c<?php echo $this->baseUrl('css/ie.css'); ?>" type="text/css" media="screen" />
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
	<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.23/jquery-ui.min.js"></script>
	<script src="<?php echo $this->baseUrl('tiny_mce/jquery.tinymce.js'); ?>" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl('js/hideshow.js'); ?>" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl('js/jquery.tablesorter.min.js'); ?>" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl('js/jquery.equalHeight.js'); ?>" type="text/javascript"></script>
	<script type="text/javascript">
	$(document).ready(function() { 
		
	    $(".tablesorter").tablesorter(); 
    	$(".tab_content").hide();
    	
    	$("ul.tabs li:first").addClass("active").show();
    	$(".tab_content:first").show();
    
    	$("ul.tabs li").click(function() {
    		$("ul.tabs li").removeClass("active");
    		$(this).addClass("active");
    		$(".tab_content").hide();
    
    		var activeTab = $(this).find("a").attr("href");
    		$(activeTab).fadeIn();
    		return false;
    	});
    	
        $('.column').equalHeight();

        $('.required').append('<span>*</span>');

        $('.editor').tinymce({
			// Location of TinyMCE script
			script_url : '<?php echo $this->baseUrl('tiny_mce/tiny_mce.js'); ?>',

			// General options
			theme : "advanced",
			//skin: 'o2k7',
			plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist",

			// Theme options
			theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
			theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
			theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
			theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak",
			theme_advanced_toolbar_location : "top",
			theme_advanced_toolbar_align : "left",
			theme_advanced_statusbar_location : "bottom",
			theme_advanced_resizing : true,

			// Drop lists for link/image/media/template dialogs
			template_external_list_url : "lists/template_list.js",
			external_link_list_url : "lists/link_list.js",
			external_image_list_url : "lists/image_list.js",
			media_external_list_url : "lists/media_list.js",

			// Replace values for the template plugin
			template_replace_values : {
				username : "Some User",
				staffid : "991234"
			}
		});

		$('.date-picker').datepicker({
		    dateFormat : 'yy-mm-dd'
		});
        
    });
    </script>

</head>
<body>
    <?php echo $this->render('layout/header.phtml'); ?>
    <?php echo $this->render('layout/left.phtml'); ?>
    <?php echo $this->render('layout/content.phtml'); ?>
</body>
</html>