<article class="module width_full">

	<header>
		<h3 class="tabs_involved">Записи</h3>
	</header>

	<div class="tab_container">
		<table class="tablesorter" cellspacing="0">
			<thead>
				<tr>
					<th></th>
					<th>Телефон</th>
					<th>Име</th>
					<th>Дата</th>
					<th>Действия</th>
				</tr>
			</thead>
			<tbody>
                            <? foreach ($this->records as $record) { ?>
				<tr>
					<td></td>
					<td><?=$record['phone']?></td>
					<td><?=$record['name']?></td>
					<td><?=$record['date']?></td>
                                        <td>
                                            <a href="/record/edit/id/<?=$record['id']?>" target="_self"><input type="image" src="images/icn_edit.png" title="Edit"></a>
                                            <a href="/record/delete/id/<?=$record['id']?>" target="_self"><input type="image" src="images/icn_trash.png" title="Trash"></a>
                                        </td>
				</tr>
                          <? } ?>
			</tbody>
		</table>
	</div>

</article>
<!-- end of post new article -->