<article class="module width_full">

	<header>
		<h3 class="tabs_involved">Записи</h3>
	</header>

	<div class="tab_container">
		<table class="tablesorter" cellspacing="0">
			<thead>
				<tr>
					<th></th>
					<th>Телефон</th>
					<th>Име</th>
					<th>Дата</th>
					<th>Действия</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td></td>
					<td>Lorem Ipsum Dolor Sit Amet</td>
					<td>Articles</td>
					<td>5th April 2011</td>
					<td><input type="image" src="images/icn_edit.png" title="Edit"><input
						type="image" src="images/icn_trash.png" title="Trash"></td>
				</tr>
			</tbody>
		</table>
	</div>

</article>
<!-- end of post new article -->